import psycopg2

DB_URL = "postgresql://postgres:DineshK%402624@db.altsfwlvjvwffoebqlna.supabase.co:5432/postgres"

def fix_schema():
    try:
        conn = psycopg2.connect(DB_URL)
        conn.autocommit = True
        cur = conn.cursor()
        
        print("Checking ID column default...")
        cur.execute("SELECT column_default FROM information_schema.columns WHERE table_name='department' AND column_name='id'")
        default_val = cur.fetchone()[0]
        print(f"Current default: {default_val}")
        
        if default_val is None:
            print("No default value. Attempting to add identity...")
            try:
                # Try Postgres 10+ Identity
                cur.execute("ALTER TABLE department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
                print("Added IDENTITY (BY DEFAULT).")
            except Exception as e:
                print(f"Identity failed: {e}")
                # Fallback to Sequence
                try:
                    cur.execute("CREATE SEQUENCE department_id_seq")
                    cur.execute("ALTER TABLE department ALTER COLUMN id SET DEFAULT nextval('department_id_seq')")
                    
                    # Sync sequence
                    cur.execute("SELECT MAX(id) FROM department")
                    max_id = cur.fetchone()[0] or 0
                    cur.execute(f"SELECT setval('department_id_seq', {max_id})")
                    print(f"Added SEQUENCE and synced to {max_id}.")
                except Exception as e2:
                    print(f"Sequence failed: {e2}")

        conn.close()
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    fix_schema()
