-- ACADEMIC SCHEMA (Synced with B.Tech Production Schema)
-- Use Singular Table Names & UUIDs for backend compatibility

CREATE TABLE IF NOT EXISTS public.academic_year (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.course (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT NOT NULL,
    status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS public.department (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT NOT NULL,
    course_id UUID REFERENCES public.course(id),
    status TEXT DEFAULT 'active'
);

-- See academic_schema_btech.sql for the full production schema including Timetables, Alerts, etc.

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, -- e.g., "2024-2025"
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    is_current BOOLEAN DEFAULT FALSE, -- Only one row should be true
    created_by UUID REFERENCES auth.users(id), -- Assuming Supabase Auth
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT date_check CHECK (end_date > start_date)
);

-- MODULE 2: SEMESTER SETUP
CREATE TABLE IF NOT EXISTS semesters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id BIGINT REFERENCES academic_years(id) ON DELETE CASCADE,
    name TEXT NOT NULL, -- "Semester 1", "Odd", "Even"
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    sequence_number INT, -- 1, 2, 3...
    status TEXT CHECK (status IN ('Upcoming', 'Active', 'Closed')) DEFAULT 'Upcoming',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT sem_date_check CHECK (end_date > start_date)
);

-- MODULE 3: DEPARTMENT SETUP
CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE, -- "Computer Science"
    code TEXT NOT NULL UNIQUE, -- "CSE"
    hod_faculty_id BIGINT REFERENCES faculty(id) ON DELETE SET NULL, -- Assuming existing table 'faculty'
    status TEXT DEFAULT 'active'
);

-- MODULE 4: COURSE / PROGRAM SETUP
CREATE TABLE IF NOT EXISTS courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT REFERENCES departments(id) ON DELETE CASCADE,
    name TEXT NOT NULL, -- "B.Tech"
    code TEXT NOT NULL,
    duration_years INT NOT NULL,
    total_semesters INT NOT NULL,
    status TEXT DEFAULT 'active'
);

-- MODULE 5: BRANCH / SPECIALIZATION SETUP
CREATE TABLE IF NOT EXISTS branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    department_id BIGINT REFERENCES departments(id), -- Redundant but fast access
    name TEXT NOT NULL, -- "Artificial Intelligence"
    code TEXT NOT NULL, -- "AI & DS"
    status TEXT DEFAULT 'active'
);

-- MODULE 6: ACADEMIC LEVEL (Year Mapping)
CREATE TABLE IF NOT EXISTS academic_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    name TEXT NOT NULL, -- "1st Year", "2nd Year"
    sequence_number INT NOT NULL, -- 1, 2, 3, 4
    status TEXT DEFAULT 'active'
);

-- MODULE 7: SECTION / CLASS SETUP
CREATE TABLE IF NOT EXISTS sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, -- "A", "B", "C"
    academic_year_id BIGINT REFERENCES academic_years(id),
    semester_id BIGINT REFERENCES semesters(id),
    course_id BIGINT REFERENCES courses(id),
    branch_id BIGINT REFERENCES branches(id),
    academic_level_id BIGINT REFERENCES academic_levels(id),
    class_teacher_id BIGINT REFERENCES faculty(id) ON DELETE SET NULL,
    max_students INT DEFAULT 60,
    status TEXT DEFAULT 'active',
    UNIQUE(academic_year_id, semester_id, branch_id, name)
);

-- MODULE 8: SUBJECT SETUP
CREATE TABLE IF NOT EXISTS subjects_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT NOT NULL,
    course_id BIGINT REFERENCES courses(id),
    branch_id BIGINT REFERENCES branches(id),
    semester_number INT, -- 1, 2, 3... Generic mapping
    credits FLOAT DEFAULT 3.0,
    subject_type TEXT CHECK (subject_type IN ('Theory', 'Lab', 'Project', 'Elective')),
    weekly_hours INT DEFAULT 4,
    status TEXT DEFAULT 'active',
    UNIQUE(code, branch_id)
);

-- MODULE 9: FACULTY-SUBJECT ALLOCATION (Active Mapping)
CREATE TABLE IF NOT EXISTS faculty_subject_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id BIGINT REFERENCES academic_years(id),
    semester_id BIGINT REFERENCES semesters(id),
    section_id BIGINT REFERENCES sections(id),
    subject_id BIGINT REFERENCES subjects_master(id),
    faculty_id BIGINT REFERENCES faculty(id),
    is_primary BOOLEAN DEFAULT TRUE, -- For Labs with multiple faculty
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(section_id, subject_id, faculty_id)
);

-- MODULE 10: ACADEMIC CALENDAR
CREATE TABLE IF NOT EXISTS academic_calendar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id BIGINT REFERENCES academic_years(id),
    semester_id BIGINT REFERENCES semesters(id),
    title TEXT NOT NULL,
    event_type TEXT CHECK (event_type IN ('Instruction', 'Exam', 'Evaluation', 'Result', 'Other')),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    applicable_to TEXT DEFAULT 'All' -- 'All', 'Faculty', 'Student'
);

-- MODULE 11: HOLIDAYS
CREATE TABLE IF NOT EXISTS holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id BIGINT REFERENCES academic_years(id),
    name TEXT NOT NULL,
    date DATE NOT NULL,
    type TEXT CHECK (type IN ('National', 'Regional', 'Institutional', 'Emergency')),
    applicable_to TEXT DEFAULT 'All'
);

-- MODULE 12: WORKING HOURS / PERIODS
CREATE TABLE IF NOT EXISTS periods_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id BIGINT REFERENCES academic_years(id),
    name TEXT NOT NULL, -- "Period 1"
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    type TEXT CHECK (type IN ('Class', 'Break', 'Lunch')),
    sequence_number INT NOT NULL
);

-- MODULE 13 & 14: RULES CONFIGURATION
CREATE TABLE IF NOT EXISTS academic_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id BIGINT REFERENCES academic_years(id) UNIQUE,
    
    -- Timetable Rules
    max_periods_per_day INT DEFAULT 8,
    lab_continuous_periods INT DEFAULT 3,
    faculty_daily_limit INT DEFAULT 4,
    
    -- Attendance Rules
    min_attendance_percentage FLOAT DEFAULT 75.0,
    attendance_lock_days INT DEFAULT 2, -- Lock attendance updates after 2 days
    
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
